photobyanni/about/urls.py
from django.urls import path
from . import views


app_name = "about"


urlpatterns = [
    path("", views.about, name="about_page"),
]

photobyanni/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("about/", include("about.urls")),
    path("services/", include("services.urls")),
    path("contacts/", include("contacts.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

photobyanni/contacts/urls.py
from django.urls import path
from . import views


app_name = "contacts"


urlpatterns = [
    path("", views.contacts, name="contacts_page"),
]

photobyanni/home/urls.py
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path("", views.home, name="home_page"),
]

photobyanni/services/urls.py
from django.urls import path
from . import views


app_name = "services"


urlpatterns = [
    path("", views.services, name="services_page"),
]

photobyanni/about/models.py
from django.db import models

# Create your models here.

photobyanni/contacts/models.py
from django.db import models

# Create your models here.

photobyanni/home/models.py
from django.db import models

# Create your models here.

photobyanni/services/models.py
from django.db import models

# Create your models here.

photobyanni/about/views.py
from django.shortcuts import render


def about(request):
    return render(request, "about/about.html")

photobyanni/contacts/views.py
from django.shortcuts import render


def contacts(request):
    return render(request, "contacts/contacts.html")

photobyanni/home/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home/home.html")

photobyanni/services/views.py
from django.shortcuts import render


def services(request):
    return render(request, "services/services.html")

photobyanni/about/templates/about/about.html
<!--Подключение шаблона и static-->
{% extends "base/base.html" %}
{% load static %}


<!--Заголовок этой страницы-->
{% block title %}About Me{% endblock title %}


<!--Подключение стилей для этой страницы-->
{% block styles %}
<link rel="stylesheet" href="{% static 'about/css/about.css' %}">
{% endblock styles %}


<!--Блок main-->
{% block main %}
<div class="container about">
    <button class="about__close-btn" type="button">X</button>
    <div class="about__inner-container">
        <img class="about__pic" src="{% static 'about/images/about-01-504x369.jpg' %}" width="245" height="180" alt="Агафья Глифинская">
        <h2>Who I Am</h2>
        <h3>BERMODI TEMPORA INCIDUNT UT LABORE ET DOLORE MAGNA MALIQUAM</h3>
        <p>Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incidunt ut labore et dolore magnam. Naliquam quaerat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur.</p>
        <button class="about__more" type="button">more<span> ></span> </button>
    </div>
</div>
<div class="container about about__inner hide">
    <button class="about__close-btn" type="button">X</button>
    <div class="about__inner-container">
        <h2>A Few Words About Me</h2>
        <p>Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae.
Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea commodi consequatur. Aquis autem vel eum iure reprehenderit, muytasas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempo. Asas dresasaser. Esse, quam nihil molestiae consequatur, vel illum. Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore t dolore magnam. Naliquam quae. Rat voleneni ullam corporis suscipit labasic ut aliquidea</p>
    </div>
</div>
{% endblock main %}

photobyanni/contacts/templates/contacts/contacts.html
<!--Подключение шаблона и static-->
{% extends "base/base.html" %}
{% load static %}


<!--Заголовок этой страницы-->
{% block title %}Contacts{% endblock title %}


<!--Подключение стилей для этой страницы-->
{% block styles %}
<link rel="stylesheet" href="{% static 'contacts/css/contacts.css' %}">
{% endblock styles %}


<!--Блок main-->
{% block main %}
<div class="container about">
    <button class="about__close-btn" type="button">X</button>
    <div class="about__inner-container">
        <h2 class="services__title">Contact Info</h2>
        <div>
            <p class="services__description">My Number:</p>
            <a href="tel:+380994043257" class="services__description-link">0994043257</a>
        </div>
        <div>
            <p class="services__description">E-Mail:</p>
            <a href="mailto:rybak@bmtp.com" class="services__description-link">rybak@bmtp.com</a>
        </div>
        <p>or fill the form below to contact me or if you have some questions</p>
        <form class="services__form" action="#">
            <input name="user_name" class="services__form-input" type="text" placeholder="Your Name *" required minlength="2">
            <input name="user_email" class="services__form-input" type="email" placeholder="Your e-mail *" required>
            <input name="user_phone" class="services__form-input" type="number" placeholder="Your phone number *" required>
            <textarea name="user_message" class="services__form-textarea" name="" cols="30" rows="10" placeholder="Write your message... *" required minlength="5" maxlength="200"></textarea>
            <div class="form__btn-wrapper">
                <button class="form__btn">Send message</button>
                <p class="form__description"></p>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

photobyanni/home/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock title%}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'home/images/favicon.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/footer.css' %}">
    {% block styles %}{% endblock styles %}
</head>

    <body>
        <div class= "bg-image"></div>
        <header class="header container">
            <div class="header__container">
                <div class="logo__container">
                    <a href="{% static 'url home:home_page' %}" class="logo">KELISSA SMITH
                    <span class="logo__descr">LIFESTYLE PHOTOGRAPHER</span></a>
                </div>
                <p class="header__description">I am a professional <span>specializing in lifestyle</span> photography.</p>
            </div>
            <ul class="header__list">
                <li class="header__list-item"><div class="kapec"><a class="header__list-link" href="{% url 'home:home_page' %}">Gallery</a><a class="header__list-link transparent" href="{% url 'home:home_page' %}">Gallery</a></div></li>
                <li class="header__list-item"><div class="kapec"><a class="header__list-link" href="{% url 'about:about_page' %}">About me</a><a class="header__list-link transparent" href="{% url 'about:about_page' %}">About me</a></div></li>
                <li class="header__list-item"><div class="kapec"><a class="header__list-link" href="{% url 'services:services_page' %}">Services</a><a class="header__list-link transparent" href="{% url 'services:services_page' %}">Services</a></div></li>
                <li class="header__list-item"><div class="kapec"><a class="header__list-link" href="{% url 'contacts:contacts_page' %}">Contacts</a><a class="header__list-link transparent" href="{% url 'contacts:contacts_page' %}">Contacts</a></div></li>
            </ul>
        </header>
        <main class="container main-container">

        {% block main %}
        {% endblock main %}

        </main>
        <footer class="footer">
            <div class="footer__dark-line"></div>
            <div class="container footer__container">
                <ul class="footer__list">
                    <li class="footer__list-item"><a class="footer__list-link" href="#">
                        <!-- <object type="image/svg+xml" data="./images/icons/facebook.svg" class="footer__svg"></object> -->
                        <svg class="footer__icon">
                            <use href="{% static 'home/images/icons/sprite.svg#icon-facebook' %}"></use>
                        </svg>
                    <p class="visually-hidden">facebook</p></a></li>
                    <li class="footer__list-item"><a class="footer__list-link" href="#">
                        <svg class="footer__icon">
                            <use href="{% static 'home/images/icons/sprite.svg#icon-twitter' %}"></use>
                        </svg>
                    <p class="visually-hidden">tweeter</p></a></li>
                    <li class="footer__list-item"><a class="footer__list-link" href="#">
                        <svg class="footer__icon">
                            <use href="{% static 'home/images/icons/sprite.svg#icon-google-plus' %}"></use>
                        </svg>
                    <p class="visually-hidden">google+</p></a></li>
                    <li class="footer__list-item"><a class="footer__list-link" href="#">
                        <svg class="footer__icon">
                            <use href="{% static 'home/images/icons/sprite.svg#icon-vimeo' %}"></use>
                        </svg>
                    <p class="visually-hidden">vimeo</p></a></li>
                    <li class="footer__list-item"><a class="footer__list-link" href="#">
                        <svg class="footer__icon">
                            <use href="{% static 'home/images/icons/sprite.svg#icon-youtube' %}"></use>
                        </svg>
                    <p class="visually-hidden">you-tube</p></a></li>
                    <li class="footer__list-item"><a class="footer__list-link" href="#">
                        <svg class="footer__icon">
                            <use href="{% static 'home/images/icons/sprite.svg#icon-pinterest' %}"></use>
                        </svg>
                    <p class="visually-hidden">pinterest</p></a></li>
                </ul>
                <p class="footer__descr">©  2020 . <a href="#">Privacy Policy</a></p>
            </div>
        </footer>

    </body>
</html>

photobyanni/home/templates/home/home.html
<!--Подключение шаблона и static-->
{% extends "base/base.html" %}
{% load static %}


<!--Заголовок этой страницы-->
{% block title %}Gallery{% endblock title %}


<!--Блок main-->
{% block main %}
<ul class='main__list'>
    <li class='main__list-item'><img src="{% static 'home/images/lifestyle-mob180x180.jpg' %}" alt="Lifestyle">
        <div class="main__descr-wrap"><p class="main__list-descr">Lifestyle</p></div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </li>
    <li class='main__list-item'><img src="{% static 'home/images/portrait-mob180x180.jpg' %}" alt="portrait">
        <div class="main__descr-wrap"><p class="main__list-descr">Portrait</p></div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </li>
    <li class='main__list-item'><img src="{% static 'home/images/fashion-mob180x180.jpg' %}" alt="fashion">
        <div class="main__descr-wrap"><p class="main__list-descr">Fashion</p></div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </li>
    <li class='main__list-item'><img src="{% static 'home/images/nature-mob180x180.jpg' %}" alt="nature">
    <div class="main__descr-wrap"><p class="main__list-descr">Nature</p></div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </li>
    <li class='main__list-item'><img src="{% static 'home/images/citylife-mob180x180.jpg' %}" alt="city life">
    <div class="main__descr-wrap"><p class="main__list-descr">City Life</p></div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </li>
</ul>
{% endblock main %}

photobyanni/services/templates/services/services.html
<!--Подключение шаблона и static-->
{% extends "base/base.html" %}
{% load static %}


<!--Заголовок этой страницы-->
{% block title %}Services{% endblock title %}


<!--Подключение стилей для этой страницы-->
{% block styles %}
<link rel="stylesheet" href="{% static 'services/css/services.css' %}">
{% endblock styles %}


<!--Блок main-->
{% block main %}
<div class="container about">
    <button class="about__close-btn" type="button">X</button>
    <div class="about__inner-container">
        <h2 class="services__title">Services Overview</h2>
        <ul class="services__list">
            <li class="services__list-item services__icon clock-icon">
                <h3 class="services__list-title">BERMODI TEMPORA INCIDUNT UT LABORE ET DOLORE MAGNA MALIQUAM</h3>
                <p class="services__list-paragraph">Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore et dolore magnam. Naliquam quae.</p>
            </li>
            <li class="services__list-item services__icon cloud-icon">
                <h3 class="services__list-title">CIDUNT UT LABORE T DOLORE MAGNA MALIQUA MQUAERAT VOLENENI.</h3>
                <p class="services__list-paragraph">Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore et dolore magnam. Naliquam quae.</p>
            </li>
            <li class="services__list-item services__icon bell-icon">
                <h3 class="services__list-title">EMPORA INCIDUNT UT LABORE ET DOLORE MAGNA MALIQUAM LROEP OIRTA.</h3>
                <p class="services__list-paragraph">Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore et dolore magnam. Naliquam quae.</p>
            </li>
            <li class="services__list-item services__icon picture-icon">
                <h3 class="services__list-title">DUNT UT LABORE ET DOLORE MAGNA ALIQUAM LROEP OIRTA LREO PROTA.</h3>
                <p class="services__list-paragraph">Dastqui dolorem ipsumquia dolsitmet conse tequam eius. Asmodi tempora incid. Dent ut labore et dolore magnam. Naliquam quae.</p>
            </li>
        </ul>
    </div>
</div>
{% endblock main %}